site_name: Oblix SDK Documentation
site_url: https://documentation.oblix.ai
edit_uri: edit/main/docs/
site_description: Intelligent AI model orchestration between local and cloud models
site_author: Oblix AI

theme:
  name: material
  custom_dir: docs/overrides
  favicon: assets/favicon.png
  logo: assets/oblixlogo.png
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  
  features:
    - content.code.copy
    - navigation.tabs  # Enable tabs at the top
    - navigation.tabs.sticky  # Keep tabs visible when scrolling
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - redirects:
      redirect_maps:
        'index.md': 'getting-started/index.md'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oblix-ai/docs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/oblixai
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/oblixai

extra_css:
  - stylesheets/extra.css

nav:
  # Documentation tab
  - Documentation:
    - Getting Started:
      - Overview: getting-started/index.md
      - Quickstart: getting-started/quickstart.md
      - Installation: getting-started/installation.md
      - Authentication: getting-started/authentication.md
    - Providers:
      - Overview: providers/index.md
      - OpenAI: providers/openai.md
      - Claude: providers/claude.md
      - Ollama: providers/ollama.md
    - Examples:
      - Overview: examples/index.md
      - Basic Usage: examples/basic-usage.md
      - Hybrid Execution: examples/hybrid-execution.md
      - Advanced Session Management: examples/session-management-advanced.md
#    - Integration Guides:
#      - Overview: integration-guides/index.md
#      - FastAPI Server: integration-guides/fastapi-server.md
#      - Frontend Integration: integration-guides/frontend-integration.md
#      - Troubleshooting: integration-guides/troubleshooting.md
    - CLI Reference: 
      - Overview: cli/index.md
  
  # Core Concepts tab
  - Core Concepts:
    - Overview: core-concepts/index.md
    - Orchestration: core-concepts/orchestration.md
    - Agents: core-concepts/agents.md
    - Session Management: core-concepts/session-management.md
    
  # API Reference tab with code icon in the title
  - ">_API Reference":
    - Overview: api-reference/index.md
    - OblixClient: api-reference/oblix-client.md
    - ModelType: api-reference/model-types.md
    - Agents: api-reference/agents.md
    - REST Endpoints: api-reference/rest-endpoints.md
